
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point PC[31] PC[31] -type PI PI
add mapped point PC[30] PC[30] -type PI PI
add mapped point PC[29] PC[29] -type PI PI
add mapped point PC[28] PC[28] -type PI PI
add mapped point PC[27] PC[27] -type PI PI
add mapped point PC[26] PC[26] -type PI PI
add mapped point PC[25] PC[25] -type PI PI
add mapped point PC[24] PC[24] -type PI PI
add mapped point PC[23] PC[23] -type PI PI
add mapped point PC[22] PC[22] -type PI PI
add mapped point PC[21] PC[21] -type PI PI
add mapped point PC[20] PC[20] -type PI PI
add mapped point PC[19] PC[19] -type PI PI
add mapped point PC[18] PC[18] -type PI PI
add mapped point PC[17] PC[17] -type PI PI
add mapped point PC[16] PC[16] -type PI PI
add mapped point PC[15] PC[15] -type PI PI
add mapped point PC[14] PC[14] -type PI PI
add mapped point PC[13] PC[13] -type PI PI
add mapped point PC[12] PC[12] -type PI PI
add mapped point PC[11] PC[11] -type PI PI
add mapped point PC[10] PC[10] -type PI PI
add mapped point PC[9] PC[9] -type PI PI
add mapped point PC[8] PC[8] -type PI PI
add mapped point PC[7] PC[7] -type PI PI
add mapped point PC[6] PC[6] -type PI PI
add mapped point PC[5] PC[5] -type PI PI
add mapped point PC[4] PC[4] -type PI PI
add mapped point PC[3] PC[3] -type PI PI
add mapped point PC[2] PC[2] -type PI PI
add mapped point PC[1] PC[1] -type PI PI
add mapped point PC[0] PC[0] -type PI PI
add mapped point burst_addr[31] burst_addr[31] -type PI PI
add mapped point burst_addr[30] burst_addr[30] -type PI PI
add mapped point burst_addr[29] burst_addr[29] -type PI PI
add mapped point burst_addr[28] burst_addr[28] -type PI PI
add mapped point burst_addr[27] burst_addr[27] -type PI PI
add mapped point burst_addr[26] burst_addr[26] -type PI PI
add mapped point burst_addr[25] burst_addr[25] -type PI PI
add mapped point burst_addr[24] burst_addr[24] -type PI PI
add mapped point burst_addr[23] burst_addr[23] -type PI PI
add mapped point burst_addr[22] burst_addr[22] -type PI PI
add mapped point burst_addr[21] burst_addr[21] -type PI PI
add mapped point burst_addr[20] burst_addr[20] -type PI PI
add mapped point burst_addr[19] burst_addr[19] -type PI PI
add mapped point burst_addr[18] burst_addr[18] -type PI PI
add mapped point burst_addr[17] burst_addr[17] -type PI PI
add mapped point burst_addr[16] burst_addr[16] -type PI PI
add mapped point burst_addr[15] burst_addr[15] -type PI PI
add mapped point burst_addr[14] burst_addr[14] -type PI PI
add mapped point burst_addr[13] burst_addr[13] -type PI PI
add mapped point burst_addr[12] burst_addr[12] -type PI PI
add mapped point burst_addr[11] burst_addr[11] -type PI PI
add mapped point burst_addr[10] burst_addr[10] -type PI PI
add mapped point burst_addr[9] burst_addr[9] -type PI PI
add mapped point burst_addr[8] burst_addr[8] -type PI PI
add mapped point burst_addr[7] burst_addr[7] -type PI PI
add mapped point burst_addr[6] burst_addr[6] -type PI PI
add mapped point burst_addr[5] burst_addr[5] -type PI PI
add mapped point burst_addr[4] burst_addr[4] -type PI PI
add mapped point burst_addr[3] burst_addr[3] -type PI PI
add mapped point burst_addr[2] burst_addr[2] -type PI PI
add mapped point burst_addr[1] burst_addr[1] -type PI PI
add mapped point burst_addr[0] burst_addr[0] -type PI PI
add mapped point burst_len[7] burst_len[7] -type PI PI
add mapped point burst_len[6] burst_len[6] -type PI PI
add mapped point burst_len[5] burst_len[5] -type PI PI
add mapped point burst_len[4] burst_len[4] -type PI PI
add mapped point burst_len[3] burst_len[3] -type PI PI
add mapped point burst_len[2] burst_len[2] -type PI PI
add mapped point burst_len[1] burst_len[1] -type PI PI
add mapped point burst_len[0] burst_len[0] -type PI PI
add mapped point burst_req burst_req -type PI PI
add mapped point burst_ready burst_ready -type PI PI

//output ports
add mapped point Instruction_Code[31] Instruction_Code[31] -type PO PO
add mapped point Instruction_Code[30] Instruction_Code[30] -type PO PO
add mapped point Instruction_Code[29] Instruction_Code[29] -type PO PO
add mapped point Instruction_Code[28] Instruction_Code[28] -type PO PO
add mapped point Instruction_Code[27] Instruction_Code[27] -type PO PO
add mapped point Instruction_Code[26] Instruction_Code[26] -type PO PO
add mapped point Instruction_Code[25] Instruction_Code[25] -type PO PO
add mapped point Instruction_Code[24] Instruction_Code[24] -type PO PO
add mapped point Instruction_Code[23] Instruction_Code[23] -type PO PO
add mapped point Instruction_Code[22] Instruction_Code[22] -type PO PO
add mapped point Instruction_Code[21] Instruction_Code[21] -type PO PO
add mapped point Instruction_Code[20] Instruction_Code[20] -type PO PO
add mapped point Instruction_Code[19] Instruction_Code[19] -type PO PO
add mapped point Instruction_Code[18] Instruction_Code[18] -type PO PO
add mapped point Instruction_Code[17] Instruction_Code[17] -type PO PO
add mapped point Instruction_Code[16] Instruction_Code[16] -type PO PO
add mapped point Instruction_Code[15] Instruction_Code[15] -type PO PO
add mapped point Instruction_Code[14] Instruction_Code[14] -type PO PO
add mapped point Instruction_Code[13] Instruction_Code[13] -type PO PO
add mapped point Instruction_Code[12] Instruction_Code[12] -type PO PO
add mapped point Instruction_Code[11] Instruction_Code[11] -type PO PO
add mapped point Instruction_Code[10] Instruction_Code[10] -type PO PO
add mapped point Instruction_Code[9] Instruction_Code[9] -type PO PO
add mapped point Instruction_Code[8] Instruction_Code[8] -type PO PO
add mapped point Instruction_Code[7] Instruction_Code[7] -type PO PO
add mapped point Instruction_Code[6] Instruction_Code[6] -type PO PO
add mapped point Instruction_Code[5] Instruction_Code[5] -type PO PO
add mapped point Instruction_Code[4] Instruction_Code[4] -type PO PO
add mapped point Instruction_Code[3] Instruction_Code[3] -type PO PO
add mapped point Instruction_Code[2] Instruction_Code[2] -type PO PO
add mapped point Instruction_Code[1] Instruction_Code[1] -type PO PO
add mapped point Instruction_Code[0] Instruction_Code[0] -type PO PO
add mapped point burst_data[31] burst_data[31] -type PO PO
add mapped point burst_data[30] burst_data[30] -type PO PO
add mapped point burst_data[29] burst_data[29] -type PO PO
add mapped point burst_data[28] burst_data[28] -type PO PO
add mapped point burst_data[27] burst_data[27] -type PO PO
add mapped point burst_data[26] burst_data[26] -type PO PO
add mapped point burst_data[25] burst_data[25] -type PO PO
add mapped point burst_data[24] burst_data[24] -type PO PO
add mapped point burst_data[23] burst_data[23] -type PO PO
add mapped point burst_data[22] burst_data[22] -type PO PO
add mapped point burst_data[21] burst_data[21] -type PO PO
add mapped point burst_data[20] burst_data[20] -type PO PO
add mapped point burst_data[19] burst_data[19] -type PO PO
add mapped point burst_data[18] burst_data[18] -type PO PO
add mapped point burst_data[17] burst_data[17] -type PO PO
add mapped point burst_data[16] burst_data[16] -type PO PO
add mapped point burst_data[15] burst_data[15] -type PO PO
add mapped point burst_data[14] burst_data[14] -type PO PO
add mapped point burst_data[13] burst_data[13] -type PO PO
add mapped point burst_data[12] burst_data[12] -type PO PO
add mapped point burst_data[11] burst_data[11] -type PO PO
add mapped point burst_data[10] burst_data[10] -type PO PO
add mapped point burst_data[9] burst_data[9] -type PO PO
add mapped point burst_data[8] burst_data[8] -type PO PO
add mapped point burst_data[7] burst_data[7] -type PO PO
add mapped point burst_data[6] burst_data[6] -type PO PO
add mapped point burst_data[5] burst_data[5] -type PO PO
add mapped point burst_data[4] burst_data[4] -type PO PO
add mapped point burst_data[3] burst_data[3] -type PO PO
add mapped point burst_data[2] burst_data[2] -type PO PO
add mapped point burst_data[1] burst_data[1] -type PO PO
add mapped point burst_data[0] burst_data[0] -type PO PO
add mapped point burst_valid burst_valid -type PO PO
add mapped point burst_last burst_last -type PO PO

//inout ports




//Sequential Pins
add mapped point burst_last/q burst_last_reg/Q -type DFF DFF
add mapped point beat_count[7]/q beat_count_reg[7]/Q -type DFF DFF
add mapped point beat_count[6]/q beat_count_reg[6]/Q -type DFF DFF
add mapped point beat_count[5]/q beat_count_reg[5]/Q -type DFF DFF
add mapped point beat_count[4]/q beat_count_reg[4]/Q -type DFF DFF
add mapped point beat_count[3]/q beat_count_reg[3]/Q -type DFF DFF
add mapped point burst_data[30]/q burst_data_reg[30]/Q -type DFF DFF
add mapped point current_addr[7]/q current_addr_reg[7]/Q -type DFF DFF
add mapped point burst_data[4]/q burst_data_reg[4]/Q -type DFF DFF
add mapped point burst_data[21]/q burst_data_reg[21]/Q -type DFF DFF
add mapped point burst_data[22]/q burst_data_reg[22]/Q -type DFF DFF
add mapped point burst_data[23]/q burst_data_reg[23]/Q -type DFF DFF
add mapped point burst_data[24]/q burst_data_reg[24]/Q -type DFF DFF
add mapped point burst_data[25]/q burst_data_reg[25]/Q -type DFF DFF
add mapped point burst_data[26]/q burst_data_reg[26]/Q -type DFF DFF
add mapped point burst_data[27]/q burst_data_reg[27]/Q -type DFF DFF
add mapped point burst_data[28]/q burst_data_reg[28]/Q -type DFF DFF
add mapped point burst_data[29]/q burst_data_reg[29]/Q -type DFF DFF
add mapped point current_addr[6]/q current_addr_reg[6]/Q -type DFF DFF
add mapped point burst_data[31]/q burst_data_reg[31]/Q -type DFF DFF
add mapped point burst_data[0]/q burst_data_reg[0]/Q -type DFF DFF
add mapped point burst_data[1]/q burst_data_reg[1]/Q -type DFF DFF
add mapped point burst_data[2]/q burst_data_reg[2]/Q -type DFF DFF
add mapped point current_addr[2]/q current_addr_reg[2]/Q -type DFF DFF
add mapped point current_addr[3]/q current_addr_reg[3]/Q -type DFF DFF
add mapped point current_addr[4]/q current_addr_reg[4]/Q -type DFF DFF
add mapped point burst_data[3]/q burst_data_reg[3]/Q -type DFF DFF
add mapped point current_addr[5]/q current_addr_reg[5]/Q -type DFF DFF
add mapped point beat_count[1]/q beat_count_reg[1]/Q -type DFF DFF
add mapped point beat_count[2]/q beat_count_reg[2]/Q -type DFF DFF
add mapped point beat_count[0]/q beat_count_reg[0]/Q -type DFF DFF
add mapped point burst_data[6]/q burst_data_reg[6]/Q -type DFF DFF
add mapped point current_addr[9]/q current_addr_reg[9]/Q -type DFF DFF
add mapped point current_addr[10]/q current_addr_reg[10]/Q -type DFF DFF
add mapped point current_addr[11]/q current_addr_reg[11]/Q -type DFF DFF
add mapped point burst_data[7]/q burst_data_reg[7]/Q -type DFF DFF
add mapped point burst_data[8]/q burst_data_reg[8]/Q -type DFF DFF
add mapped point burst_data[9]/q burst_data_reg[9]/Q -type DFF DFF
add mapped point burst_data[10]/q burst_data_reg[10]/Q -type DFF DFF
add mapped point burst_data[11]/q burst_data_reg[11]/Q -type DFF DFF
add mapped point burst_data[12]/q burst_data_reg[12]/Q -type DFF DFF
add mapped point current_addr[8]/q current_addr_reg[8]/Q -type DFF DFF
add mapped point burst_data[14]/q burst_data_reg[14]/Q -type DFF DFF
add mapped point burst_data[15]/q burst_data_reg[15]/Q -type DFF DFF
add mapped point burst_data[16]/q burst_data_reg[16]/Q -type DFF DFF
add mapped point burst_data[17]/q burst_data_reg[17]/Q -type DFF DFF
add mapped point burst_data[18]/q burst_data_reg[18]/Q -type DFF DFF
add mapped point burst_data[19]/q burst_data_reg[19]/Q -type DFF DFF
add mapped point burst_data[20]/q burst_data_reg[20]/Q -type DFF DFF
add mapped point burst_data[13]/q burst_data_reg[13]/Q -type DFF DFF
add mapped point burst_data[5]/q burst_data_reg[5]/Q -type DFF DFF
add mapped point burst_state/q burst_state_reg/Q -type DFF DFF
add mapped point total_beats[6]/q total_beats_reg[6]/Q -type DFF DFF
add mapped point total_beats[3]/q total_beats_reg[3]/Q -type DFF DFF
add mapped point total_beats[4]/q total_beats_reg[4]/Q -type DFF DFF
add mapped point total_beats[5]/q total_beats_reg[5]/Q -type DFF DFF
add mapped point total_beats[2]/q total_beats_reg[2]/Q -type DFF DFF
add mapped point total_beats[7]/q total_beats_reg[7]/Q -type DFF DFF
add mapped point total_beats[0]/q total_beats_reg[0]/Q -type DFF DFF
add mapped point total_beats[1]/q total_beats_reg[1]/Q -type DFF DFF



//Black Boxes
add mapped point u_ram_macro u_ram_macro -type BBOX BBOX



//Empty Modules as Blackboxes
