/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module FA_Reg(clk, rst_n, a, b, cin, sum, cout);
  wire _0_;
  wire _1_;
  wire _2_;
  input a;
  wire a;
  input b;
  wire b;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output cout;
  wire cout;
  wire cout_comb;
  input rst_n;
  wire rst_n;
  output sum;
  wire sum;
  wire sum_comb;
  sky130_fd_sc_hd__inv_2 _3_ (
    .A(cin),
    .Y(_0_)
  );
  sky130_fd_sc_hd__nand2_2 _4_ (
    .A(b),
    .B(a),
    .Y(_1_)
  );
  sky130_fd_sc_hd__xnor2_2 _5_ (
    .A(b),
    .B(a),
    .Y(_2_)
  );
  sky130_fd_sc_hd__o21ai_2 _6_ (
    .A1(_0_),
    .A2(_2_),
    .B1(_1_),
    .Y(cout_comb)
  );
  sky130_fd_sc_hd__xnor2_2 _7_ (
    .A(cin),
    .B(_2_),
    .Y(sum_comb)
  );
  sky130_fd_sc_hd__dfrtp_2 _8_ (
    .CLK(clk),
    .D(sum_comb),
    .Q(sum),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _9_ (
    .CLK(clk),
    .D(cout_comb),
    .Q(cout),
    .RESET_B(rst_n)
  );
endmodule
