#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GNU="$ROOT/gnu_toolchain"
TB="$ROOT/tb_soc/tb_soc_dualcore_suite.v"
TMPDIR="${TMPDIR:-/tmp}"
REPORT="$ROOT/paper2/paper2_2/dualcore_contention_benchmark.md"

tests=(
  "test_dualcore_contention_forward_dma 32'hC2CF1001 32'hD0F00011 2 16 0 32'h00000000 0 32'h00000000 0 32'h00000000 500000"
  "test_dualcore_contention_fallback_dma 32'hC2CF2002 32'hD0F00022 2 16 0 32'h00000000 0 32'h00000000 0 32'h00000000 500000"
)

extract_metric() {
  local pattern="$1"
  local file="$2"
  grep -m1 "$pattern" "$file" | sed -E "s/.*${pattern}=([0-9a-fA-Fx]+).*/\\1/"
}

extract_line_value() {
  local prefix="$1"
  local file="$2"
  grep -m1 "$prefix" "$file" | sed -E "s/.*${prefix}=([0-9]+).*/\\1/"
}

declare -a rows=()

for item in "${tests[@]}"; do
  read -r name sig0 sig1 heartbeat dc_req aux0_check aux0 aux1_check aux1 gpio_check expect_gpio timeout <<<"$item"
  src="tests_dualcore/${name}.c"
  hex="tests_dualcore/${name}.hex"
  out="${TMPDIR}/${name}.out"
  log="${TMPDIR}/${name}.log"

  echo "== Building ${name} =="
  (
    cd "$GNU"
    ./compile_c_to_hex.sh -i "$src" -o "$hex" -c >/dev/null
  )

  echo "== Running ${name} =="
  (
    cd "$ROOT"
    iverilog -g2005 -I. \
      -DTEST_HEX="\"gnu_toolchain/${hex}\"" \
      -DSCENARIO_NAME="\"${name}\"" \
      -DEXPECT_SIG0="${sig0}" \
      -DEXPECT_SIG1="${sig1}" \
      -DHEARTBEAT_MIN="${heartbeat}" \
      -DDC_REQ_MIN="${dc_req}" \
      -DAUX0_CHECK_ENABLE="${aux0_check}" \
      -DEXPECT_AUX0="${aux0}" \
      -DAUX1_CHECK_ENABLE="${aux1_check}" \
      -DEXPECT_AUX1="${aux1}" \
      -DGPIO_CHECK_ENABLE="${gpio_check}" \
      -DEXPECT_GPIO="${expect_gpio}" \
      -DTIMEOUT_CYCLES="${timeout}" \
      -o "$out" "$TB" >/dev/null
    vvp "$out" | tee "$log"
  )

  cycles=$(extract_line_value "cycles" "$log")
  core0_dc=$(grep -m1 "core0_dc_req_count" "$log" | sed -E 's/.*core0_dc_req_count=([0-9]+) core1_dc_req_count=([0-9]+).*/\1/')
  core1_dc=$(grep -m1 "core0_dc_req_count" "$log" | sed -E 's/.*core0_dc_req_count=([0-9]+) core1_dc_req_count=([0-9]+).*/\2/')
  dcache0_line=$(grep -m1 "dcache0 peer_snp_reqs" "$log")
  dcache1_line=$(grep -m1 "dcache1 peer_snp_reqs" "$log")
  peer_reqs=$(echo "$dcache1_line" | sed -E 's/.*peer_snp_reqs=([0-9]+).*/\1/')
  peer_hits=$(echo "$dcache1_line" | sed -E 's/.*peer_snp_hits=([0-9]+).*/\1/')
  c2c_fwds=$(echo "$dcache1_line" | sed -E 's/.*c2c_fwds=([0-9]+).*/\1/')
  c2c_fill_cycles=$(echo "$dcache1_line" | sed -E 's/.*c2c_fill_cycles=([0-9]+).*/\1/')
  core0_mem_refills=$(echo "$dcache0_line" | sed -E 's/.*mem_refills=([0-9]+).*/\1/')
  core1_mem_refills=$(echo "$dcache1_line" | sed -E 's/.*mem_refills=([0-9]+).*/\1/')

  if [[ "$name" == *"forward"* ]]; then
    mode="forward-hit + DMA"
  else
    mode="fallback-refill + DMA"
  fi

  rows+=("| ${mode} | ${cycles} | ${core0_dc} | ${core1_dc} | ${peer_reqs} | ${peer_hits} | ${c2c_fwds} | ${c2c_fill_cycles} | ${core0_mem_refills} | ${core1_mem_refills} |")
  echo
done

{
  echo "# Dual-Core Contention Benchmark"
  echo
  echo "- Generated by \`run_dualcore_contention_bench.sh\`"
  echo "- Focus: compare CPU1 peer-forwarded read misses against fallback memory refills while ASCON DMA is active"
  echo
  echo "| Scenario | Cycles to PASS | Core0 DC Req | Core1 DC Req | Core1 Peer Snoop Reqs | Core1 Peer Snoop Hits | Core1 C2C Forwards | Core1 C2C Fill Cycles | Core0 Mem Refills | Core1 Mem Refills |"
  echo "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"
  for row in "${rows[@]}"; do
    echo "$row"
  done
  echo
  echo "Interpretation guide:"
  echo "- \`Core1 Peer Snoop Hits\` and \`Core1 C2C Forwards\` are the primary forwarding indicators for the consumer hart."
  echo "- \`Core0 Mem Refills\` captures the extra writeback/refill pressure introduced by the fallback-eviction setup."
  echo "- \`Cycles to PASS\` is the end-to-end completion point reported by the unified SoC TB under simultaneous CPU and ASCON DMA activity."
} > "$REPORT"

echo "Report written to $REPORT"
