module dcache_snoop_ctrl (
    // ---------------------------------------------------------------------
    // Clock / Reset
    // ---------------------------------------------------------------------
    input  wire        clk,
    input  wire        rst_n,

    // ---------------------------------------------------------------------
    // Snoop request input
    // ---------------------------------------------------------------------
    input  wire [31:0] snoop_req_addr,
    input  wire [1:0]  snoop_req_cmd,
    input  wire        snoop_req_valid,
    input  wire        snoop_safe_to_accept,

    // ---------------------------------------------------------------------
    // Tag state and line data from the parent controller datapath
    // ---------------------------------------------------------------------
    input  wire        tag_hit,
    input  wire        tag_dirty_out,
    input  wire [1:0]  tag_state_out,
    input  wire [31:0] data_read_word_0,
    input  wire [31:0] data_read_word_1,
    input  wire [31:0] data_read_word_2,
    input  wire [31:0] data_read_word_3,

    // ---------------------------------------------------------------------
    // Eviction completion handshake
    // ---------------------------------------------------------------------
    input  wire        evict_done,

    // ---------------------------------------------------------------------
    // Snoop request / response handshake
    // ---------------------------------------------------------------------
    output wire        snoop_req_ready,
    output reg         snoop_resp_valid,
    output reg         snoop_resp_hit,
    output reg [127:0] snoop_resp_data,

    // ---------------------------------------------------------------------
    // Debug / lookup visibility back to the parent controller
    // ---------------------------------------------------------------------
    output wire        snoop_busy,
    output wire        snoop_lookup_active,
    output wire [5:0]  snoop_index,
    output wire [21:0] snoop_tag,

    // ---------------------------------------------------------------------
    // Tag-array update pulses generated by snoop processing
    // ---------------------------------------------------------------------
    output reg         tag_line_shared,
    output reg [5:0]   tag_line_shared_index,
    output reg         tag_line_invalidate,
    output reg [5:0]   tag_line_invalidate_index,

    // ---------------------------------------------------------------------
    // Eviction request generated by snoop invalidate on dirty lines
    // ---------------------------------------------------------------------
    output reg         snoop_evict_start,
    output reg [31:0]  snoop_evict_addr,
    output reg [31:0]  snoop_evict_data_0,
    output reg [31:0]  snoop_evict_data_1,
    output reg [31:0]  snoop_evict_data_2,
    output reg [31:0]  snoop_evict_data_3
);

    localparam [1:0]
        SNOOP_IDLE    = 2'd0,
        SNOOP_LOOKUP  = 2'd1,
        SNOOP_CAPTURE = 2'd2,
        SNOOP_EVICT   = 2'd3;

    localparam [1:0]
        SNOOP_CMD_READ       = 2'b01,
        SNOOP_CMD_INVALIDATE = 2'b10;

    localparam [1:0]
        TAG_STATE_E = 2'b10;

    reg [1:0]  snoop_state;
    reg [31:0] snoop_addr_r;
    reg [1:0]  snoop_cmd_r;
    reg [5:0]  evict_index_r;

    assign snoop_busy          = (snoop_state != SNOOP_IDLE);
    assign snoop_req_ready     = (snoop_state == SNOOP_IDLE) && snoop_safe_to_accept;
    assign snoop_index         = snoop_addr_r[9:4];
    assign snoop_tag           = snoop_addr_r[31:10];
    assign snoop_lookup_active = (snoop_state == SNOOP_LOOKUP) || (snoop_state == SNOOP_CAPTURE);

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            snoop_state               <= SNOOP_IDLE;
            snoop_addr_r              <= 32'h0;
            snoop_cmd_r               <= 2'b00;
            evict_index_r             <= 6'h0;
            snoop_resp_valid          <= 1'b0;
            snoop_resp_hit            <= 1'b0;
            snoop_resp_data           <= 128'h0;
            tag_line_shared           <= 1'b0;
            tag_line_shared_index     <= 6'h0;
            tag_line_invalidate       <= 1'b0;
            tag_line_invalidate_index <= 6'h0;
            snoop_evict_start         <= 1'b0;
            snoop_evict_addr          <= 32'h0;
            snoop_evict_data_0        <= 32'h0;
            snoop_evict_data_1        <= 32'h0;
            snoop_evict_data_2        <= 32'h0;
            snoop_evict_data_3        <= 32'h0;
        end else begin
            snoop_resp_valid    <= 1'b0;
            tag_line_shared     <= 1'b0;
            tag_line_invalidate <= 1'b0;
            snoop_evict_start   <= 1'b0;

            case (snoop_state)
                SNOOP_IDLE: begin
                    if (snoop_req_valid && snoop_req_ready) begin
                        snoop_addr_r <= snoop_req_addr;
                        snoop_cmd_r  <= snoop_req_cmd;
                        snoop_state  <= SNOOP_LOOKUP;
                    end
                end

                SNOOP_LOOKUP: begin
                    snoop_state <= SNOOP_CAPTURE;
                end

                SNOOP_CAPTURE: begin
                    snoop_resp_data <= {data_read_word_3, data_read_word_2,
                                        data_read_word_1, data_read_word_0};

                    if (tag_hit && tag_dirty_out && (snoop_cmd_r == SNOOP_CMD_INVALIDATE)) begin
                        snoop_evict_addr   <= {snoop_tag, snoop_index, 4'b0000};
                        snoop_evict_data_0 <= data_read_word_0;
                        snoop_evict_data_1 <= data_read_word_1;
                        snoop_evict_data_2 <= data_read_word_2;
                        snoop_evict_data_3 <= data_read_word_3;
                        evict_index_r      <= snoop_index;
                        snoop_evict_start  <= 1'b1;
                        snoop_state        <= SNOOP_EVICT;
                    end else begin
                        snoop_resp_valid <= 1'b1;
                        snoop_resp_hit   <= tag_hit;
                        if (tag_hit && (snoop_cmd_r == SNOOP_CMD_READ) &&
                            (tag_state_out == TAG_STATE_E)) begin
                            tag_line_shared       <= 1'b1;
                            tag_line_shared_index <= snoop_index;
                        end
                        if (tag_hit && (snoop_cmd_r == SNOOP_CMD_INVALIDATE)) begin
                            tag_line_invalidate       <= 1'b1;
                            tag_line_invalidate_index <= snoop_index;
                        end
                        snoop_state <= SNOOP_IDLE;
                    end
                end

                SNOOP_EVICT: begin
                    if (evict_done) begin
                        snoop_resp_valid          <= 1'b1;
                        snoop_resp_hit            <= 1'b1;
                        tag_line_invalidate       <= 1'b1;
                        tag_line_invalidate_index <= evict_index_r;
                        snoop_state               <= SNOOP_IDLE;
                    end
                end

                default: begin
                    snoop_state <= SNOOP_IDLE;
                end
            endcase
        end
    end
endmodule
