alu.v
ascon_axi_slave.v
ascon_CONSTANT_ADDITION.v
ascon_CONTROLLER.v
ascon_CORE.v
ascon_datapath.v
ascon_dma.v
ascon_INITIALIZATION.v
ascon_LINEAR_DIFFUSION.v
ascon_PERMUTATION.v
ascon_ROUND_COMB.v
ascon_SBOX_PIPELINED.v
ascon_STATE_REGISTER.v
ascon_SUBTITUTION_LAYER.v
ascon_TAG_COMPARATOR.v
ascon_TAG_GENERATOR.v
ascon_top.v
axi4_addr_decoder.v
axi4_crossbar_5m12s.v
axi4_decerr_slave.v
axi4_master_mux_5m.v
axi_width_converter_64to32.v
boot_ctrl.v
boot_fsm.v
boot_rom.v
branch_logic.v
clint.v
clk_buf.v
clk_reset_ctrl.v
control.v
cpu_core.v
data_mem_axi_slave.v
data_mem_burst.v
dcache_axi_interface.v
dcache_controller.v
dcache_data_array.v
dcache_tag_array.v
dcache_top.v
dma_arbiter.v
dma_axi_master.v
dma_channel.v
dma_ctrl_fsm.v
dma_ctrl.v
dma_read_engine.v
dma_reg_slave.v
dma_write_engine.v
forwarding_unit.v
gpio_iocell.v
gpio_regfile.v
gpio_top.v
hazard_detection.v
icache_axi_interface.v
icache_controller.v
icache_data_array.v
icache_tag_array.v
icache_top.v
IFU.v
imm_gen.v
inst_mem_axi_slave.v
inst_mem.v
jtag_debug_top.v
jtag_dtm.v
jtag_tap.v
LSU.v
otp_stub_slave.v
PIPELINE_REG_EX_MEM.v
PIPELINE_REG_EX_WB.v
PIPELINE_REG_ID_EX.v
PIPELINE_REG_IF_ID.v
PIPELINE_REG_MEM_WB.v
plic_gateway.v
plic_priority_encoder.v
plic_regfile.v
plic_top.v
por_stretcher.v
reg_file.v
reset_sync.v
riscv_cpu_core_v2.v
riscv_dm.v
riscv_multiplier.v
soc_ctrl_slave.v
soc_hs.v
soc_top.v
soft_rst_sync.v
spi_axi_slave.v
spi_core.v
spi_top.v
sync_fifo.v
timer_channel.v
timer_regfile.v
timer_top.v
uart_axi_slave.v
uart_baud_gen.v
uart_boot_ctrl.v
uart_fifo.v
uart_irq_gen.v
uart_rx.v
uart_top.v
uart_tx.v
wdt_core.v
