// Auto-generated by OpenLane
module FA_Reg(
`ifdef USE_POWER_PINS
  inout VGND,
  inout VPWR,
`endif
  input clk,
  input rst_n,
  input a,
  input b,
  input cin,
  output sum,
  output cout
);
endmodule
